# Generated by Django 3.2.9 on 2021-11-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('gift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('points_spent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Points',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('user_point_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField()),
                ('deposit_reason', models.SmallIntegerField(null=True)),
                ('withdrawal_reason', models.SmallIntegerField(null=True)),
                ('points', models.DecimalField(decimal_places=0, max_digits=15)),
                ('transacted_at', models.DateTimeField()),
                ('points_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Gifts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('user_gift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField()),
                ('used_at', models.DateTimeField(null=True)),
                ('gift_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='point.gifts')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Points_Packages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('points_package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('apple_product_id', models.CharField(max_length=255, null=True)),
                ('google_product_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('points', models.DecimalField(decimal_places=0, max_digits=15)),
                ('display_order', models.SmallIntegerField()),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Points_Package_Purchase_Histories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('purchased_at', models.DateTimeField()),
                ('apple_trans_id', models.CharField(max_length=255)),
                ('google_trans_id', models.CharField(max_length=255)),
                ('apple_receipt', models.TextField()),
                ('google_receipt', models.TextField()),
                ('points_package_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='point.points_packages')),
                ('user_point_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='point.user_points')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point_Spending_Histories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('spend_at', models.DateTimeField()),
                ('user_gift_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='point.user_gifts')),
                ('user_point_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='point.user_points')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gift_Tipping_Histories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points_equivalent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('to_user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel')),
                ('user_gift_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='point.user_gifts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gift_Purchased_Histories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points_spent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('purchased_at', models.DateTimeField()),
                ('user_gift_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='point.user_gifts')),
                ('user_point_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='point.user_points')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
