# Generated by Django 3.2.9 on 2021-11-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('is_elected', models.SmallIntegerField()),
                ('is_purchased', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event_Authorized_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('event_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_private', models.SmallIntegerField()),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('is_archived', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Image_Paths',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('dir_path', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Image Paths',
            },
        ),
        migrations.CreateModel(
            name='Performances',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('performance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('streaming_method', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('capacity', models.IntegerField(null=True)),
                ('ticket_available_flag', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket_Purchase_Histories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('point_amount', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_type', models.CharField(max_length=15, null=True)),
                ('purchased_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(null=True)),
                ('receipt_number', models.CharField(max_length=32)),
                ('haraikomi_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket_Purchased_Reservations',
            fields=[
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('number_of_tickets', models.IntegerField()),
                ('reservation_at', models.DateTimeField()),
                ('is_purchased', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('points_required', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('drawing_flag', models.SmallIntegerField()),
                ('drawing_application_datetime', models.DateTimeField(null=True)),
                ('drawing_status', models.SmallIntegerField()),
                ('stamp_available_flag', models.SmallIntegerField()),
                ('max_number_of_tickets', models.IntegerField()),
                ('number_of_issued_tickets', models.IntegerField()),
                ('is_seat_id_assigned', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Tickets',
            fields=[
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('user_ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_settled', models.IntegerField()),
                ('seat_id', models.CharField(max_length=255, null=True)),
                ('expires_in', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
                ('used_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.tickets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
