# Generated by Django 3.2.9 on 2021-11-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('master_data', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tickets',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='performance_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.events'),
        ),
        migrations.AddField(
            model_name='ticket_purchased_reservations',
            name='ticket_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.tickets'),
        ),
        migrations.AddField(
            model_name='ticket_purchased_reservations',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel'),
        ),
        migrations.AddField(
            model_name='ticket_purchase_histories',
            name='user_ticket_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.user_tickets'),
        ),
        migrations.AddField(
            model_name='performances',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.events'),
        ),
        migrations.AddField(
            model_name='image_paths',
            name='box_notification_trans_content_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='img_path_related', to='master_data.box_notification_transaction_contents'),
        ),
        migrations.AddField(
            model_name='image_paths',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_path_related', to='event.events'),
        ),
        migrations.AddField(
            model_name='image_paths',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_path_related', to='user.useraccountmodel'),
        ),
        migrations.AddField(
            model_name='events',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.clients'),
        ),
        migrations.AddField(
            model_name='event_authorized_user',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.clients'),
        ),
        migrations.AddField(
            model_name='event_authorized_user',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel'),
        ),
        migrations.AddField(
            model_name='drawings',
            name='ticket_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.tickets'),
        ),
        migrations.AddField(
            model_name='drawings',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.useraccountmodel'),
        ),
    ]
