# Generated by Django 3.2.9 on 2021-11-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_User_Links',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Live_Streams',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('live_stream_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ivs_arn', models.CharField(max_length=255, null=True)),
                ('status', models.SmallIntegerField()),
                ('host_user_id', models.IntegerField()),
                ('performance_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('ingest_endpoint', models.CharField(max_length=255)),
                ('stream_key', models.CharField(max_length=255)),
                ('playback_url', models.CharField(max_length=255)),
                ('comment_available_flag', models.SmallIntegerField()),
                ('tipping_available_flag', models.SmallIntegerField()),
                ('stamps_granted', models.DecimalField(decimal_places=0, max_digits=15)),
                ('release_datetime', models.DateTimeField()),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('total_number_of_viewers', models.IntegerField(null=True)),
                ('seconds_delivered', models.DecimalField(decimal_places=0, max_digits=15)),
                ('channel_id_sd', models.CharField(max_length=255, null=True)),
                ('channel_id_fhd', models.CharField(max_length=255, null=True)),
                ('input_id_sd', models.CharField(max_length=255, null=True)),
                ('input_id_fhd', models.CharField(max_length=255, null=True)),
                ('video_url_sd', models.CharField(max_length=255, null=True)),
                ('video_url_fhd', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sent_Relations',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('live_stream_id', models.IntegerField(null=True)),
                ('email_notification_trans_content_id', models.IntegerField(null=True)),
                ('push_notification_trans_content_id', models.IntegerField(null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.events')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Live_Stream_Viewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='削除フラグ')),
                ('viewed_at', models.DateTimeField()),
                ('live_stream_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live_stream.live_streams')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
