# define punctuation
import string

PUNCTUATION = r"""#$%&()?@[]^_"""

# define prefix
MAIN_PREFIX = 'S'
LOGIN_ID_PREFIX = 'C'

# Error Code
ERR_MAX_LENGTH = 'max_length'
ERR_BAD_REQUEST = 'ERR_BAD_REQUEST'
ERR_PASSWORD_EXPIRED = 'ERR_PASSWORD_EXPIRED'
ERR_WRONG_PASSWORD = 'ERR_WRONG_PASSWORD'
ERR_NOT_AUTHENTICATED = 'not_authenticated'
ERR_NOT_AUTHENTICATED_SIGN_IN = 'not_authenticated_sign_in'
ERR_PERMISSION_DENIED = 'permission_denied'
ERR_NOT_BLANK = 'blank'
ERR_INVALID_TYPE = 'invalid'
ERR_INCORRECT_TYPE = 'incorrect_type'
ERR_ACCOUNT_ALREADY_EXISTS = 'ERR_ACCOUNT_ALREADY_EXISTS'
ERR_RESOURCE_NF = 'ERR_RESOURCE_NF'
ERR_REQUIRED = 'required'
ERR_ACCOUNT_LOOKED = 'ERR_ACCOUNT_LOOKED'
ERR_EMAIL_INCORRECT_TYPE = 'ERR_EMAIL'
ERR_PHONE_INCORRECT_TYPE = 'ERR_PHONE'
ERR_EMAIL_UNIQUE = 'ERR_EMAIL_UNIQUE'
ERR_CUSTOMER_CODE_INCORRECT_TYPE = 'ERR_CUSTOMER_CODE_INCORRECT_TYPE'
ERR_RESOURCE_MAX_SIZE = 'ERR_RESOURCE_MAX_SIZE'
ERR_RESOURCE_NOT_FOUND = 'does_not_exist'
ERR_UNIQUE_FIELD = 'unique'
ERR_LIMIT_FILE_UPLOAD = 'ERR_LIMIT_FILE_UPLOAD'
ERR_ACCOUNT_NOT_ADMIN = 'ERR_ACCOUNT_NOT_ADMIN'
ERR_ACCOUNT_NOT_CONTRACTION = 'ERR_ACCOUNT_NOT_CONTRACTION'
ERR_DATE_SEARCH_INCORRECT_TYPE = 'ERR_DATE_SEARCH_INCORRECT_TYPE'
ERR_USER_IS_ACTIVE = 'ERR_USER_IS_ACTIVE'
ERR_RELATE_FIELD_LIST = 'not_a_list'
ERR_USER_INFO_IS_PENDING_APPROVE = 'ERR_USER_INFO_IS_PENDING_APPROVE'
ERR_INVALID_TYPE_NUMBER = 'ERR_INVALID_TYPE_NUMBER'
ERR_GREATER_THAN_TODAY = 'ERR_GREATER_THAN_TODAY'
ERR_SMALLER_THAN_TODAY = 'ERR_SMALLER_THAN_TODAY'
ERR_TO_GREATER_THAN_FROM = 'ERR_TO_GREATER_THAN_FROM'
ERR_FROM_GREATER_THAN_TO = 'ERR_FROM_GREATER_THAN_TO'
ERR_POSITIVE_INTEGERS = 'ERR_POSITIVE_INTEGERS'
ERR_IS_NOT_EMPTY = 'empty'
ERR_CONST_STATUS_NOT_DEL = 'ERR_CONST_STATUS_NOT_DEL'
ERR_NONE_USER_REGISTRATION = 'ERR_NONE_USER_REGISTRATION'
ERR_WRONG_MASTER_DATA_CATEGORY = 'ERR_WRONG_MASTER_DATA_CATEGORY'
ERR_ACCOUNT_TYPE_WRONG = 'ERR_ACCOUNT_TYPE_WRONG'
ERR_MAX_VALUE = 'max_value'
ERR_HALF_WIDTH_NUMBER_ONLY = 'ERR_HALF_WIDTH_NUMBER_ONLY'
ERR_FAX_INCORRECT_TYPE = 'ERR_FAX_INCORRECT_TYPE'
ERR_NOT_CONTRACTOR_USER = 'ERR_NOT_CONTRACTOR_USER'
ERR_TARGET_NOT_MATCH = 'ERR_TARGET_NOT_MATCH'
ERR_DOCUMENT_ALREADY_EXISTS = 'ERR_DOCUMENT_ALREADY_EXISTS'
ERR_CUSTOMER_CODE_ALREADY_EXISTS = 'ERR_CUSTOMER_CODE_ALREADY_EXISTS'
ERR_CONST_INTRODUCTION_ALREADY_EXISTS = 'ERR_CONST_INTRODUCTION_ALREADY_EXISTS'
ERR_CONTRACTION_USER_ALREADY_EXISTS = 'ERR_CONTRACTION_USER_ALREADY_EXISTS'

# account type
MAIN_CONTRACTOR = '001'
SUB_CONTRACTOR = '002'
MAIN_SUB_CONTRACTOR = '003'
SERVICE_CENTER = '004'
SECRETARIAT = '005'
SYSTEM_ADMINISTRATOR = '010'

# account status
NOT_JOINED = '001'
TEMPORARY_REGISTRATION = '002'
REGISTRATION = '003'
ACCOUNT_SUSPENSION = '004'
CANCELED = '005'

# construction scope
CONSTRUCTION_ONLY = '工事のみ'

# is deleted
DELETED = True
UN_DELETED = False

# construction management
NECESSARY = 1
UNNECESSARY = 0

CONST_MANAGEMENT = (
    (NECESSARY, NECESSARY),
    (UNNECESSARY, UNNECESSARY)
)

# order construction
NO_ORDERS = '受注なし'
IS_ORDERS = '受注あり'
NO_CONSTRUCTION = '工事なし'

ORDER_CONSTRUCTION = (
    (NO_ORDERS, NO_ORDERS),
    (IS_ORDERS, IS_ORDERS),
    (NO_CONSTRUCTION, NO_CONSTRUCTION),
)

ALPHABET = string.ascii_uppercase + string.digits
DIGITS = string.digits

REGEX_NUMBER_ONLY = '^[0-9]*$'
REGEX_SMALL_NUMBER_ONLY = '^[0-1]$'
REGEX_TEXT_KATAKANA = '^[ァ-ンｧ-ﾝﾞﾟー]*$'
REGEX_URL = '^http[s]?://(.)*$'
REGEX_PHONE_NUMBER = '^\d{9,11}$'

CATEGORY_ACCOUNT_STATUS = 'account_status'
CATEGORY_ACCOUNT_TYPE = 'account_type'
CATEGORY_CONST_SCOPE = 'const_scope'
CATEGORY_CONST_TYPE = 'const_type'
CATEGORY_CONST_STATUS = 'const_status'
CATEGORY_INTRO_RESULT_TYPE = 'intro_result_type'
CATEGORY_INTRO_STATUS = 'intro_status'
CATEGORY_REQUEST_TYPE = 'request_type'
CATEGORY_PROPERTY_TYPE = 'property_type'
CATEGORY_PROPERTY_DIVISION = 'property_division'
CATEGORY_MATERIAL_STRUCTURE = 'material_structure'
CATEGORY_PAYMENT_TYPE = 'payment_type'
CATEGORY_DOCUMENT_TYPE = 'document_type'
CATEGORY_NOTIFICATION_TYPE = 'notification_type'
CATEGORY_PROPERTY_STATUS = 'property_status'
CATEGORY_CONST_ADD_TYPE = 'contractor_add_type'
CATEGORY_LICENSE_TYPE = 'license_type'
CATEGORY_DOCUMENT_STATUS = 'document_status'

QUOTE_APPLY_STATUS = '申請中'

CONST_TYPE_OTHER = '008'

CONST_STATUS_REGISTRATION = '001'
CONST_STATUS_DECISION = '002'
CONST_STATUS_PURCHASE_ORDER = '003'
CONST_STATUS_CONFIRM = '004'
CONST_STATUS_EVALUATION = '005'
CONST_STATUS_CLOSE = '006'
CONST_STATUS_NOT_DEL = [CONST_STATUS_REGISTRATION, CONST_STATUS_DECISION]

CONTRACT_TEMPLATE = 0
APPLICATION_TEMPLATE = 1

DOCUMENT_ORDER = '001'
DOCUMENT_CONTRACT = '002'

CONST_INTRO_STATUS_STEP_ONE = '001'
CONST_INTRO_STATUS_STEP_TWO = '002'
CONST_INTRO_STATUS_STEP_THREE = '003'
CONST_INTRO_STATUS_STEP_FOUR = '004'
CONST_INTRO_STATUS_STEP_END = '007'

PROPERTY_REGISTER = '001'

LICENSE_999 = '999'

SUGGESTION_INTRODUCTION = 0
HISTORY_INTRODUCTION = 1

SUGGESTION_ADD_TYPE = '001'
HISTORY_ADD_TYPE = '002'

RESULT_INFO_CLOSE = '001'

DOCUMENT_PREPARING = '001'
DOCUMENT_ACCEPTED = '002'
DOCUMENT_REJECTED = '003'
DOCUMENT_REQUEST_REWRITE = '004'
DOCUMENT_ACCEPT_REWRITE = '005'
DOCUMENT_REJECT_REWRITE = '006'

# selection of step one
STEP_ONE_SEARCH_SUB_SC = 1
STEP_ONE_INTRODUCE_CONST_TO_PRIME_SC = 2
STEP_ONE_REQUEST_CANCELED = 3
STEP_ONE_CANNOT_BE_INTRODUCED = 4

# master_data_id select in step three
STEP_THREE_SETUP = '001'
STEP_THREE_INVALID = '002'
